// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tknovkrjrnlilrlerghr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRrbm92a3Jqcm5saWxybGVyZ2hyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjkyNTU3NzAsImV4cCI6MjA4NDgzMTc3MH0.niUo4ENnNXwvvpiTVbtrKdjLwy6imTsks1v5ruOy3YA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});