
-- Delete all existing recipes
DELETE FROM recipes;

-- Insert 11 new Nastea Rituals recipes
INSERT INTO recipes (title, description, image_url, category, read_time, ingredients, instructions, nutritional_benefits, is_published) VALUES

('Matcha Frappe',
'Some mornings need something colder, creamier, and slightly more extra than a latte. This is your café-style matcha frappe moment—frosty, foamy, and dangerously easy to repeat.',
'https://images.unsplash.com/photo-1544787219-7f47ccb76574?w=600&h=400&fit=crop',
'Drinks', '5 min',
ARRAY['125 g ice cubes','125 ml milk (dairy or plant-based)','6 g Nastea Rituals Matcha','Sweetener (optional)','Whipped cream (optional)','Extra matcha (optional, to dust)'],
ARRAY['Blend ice, milk, matcha, and sweetener until thick + frothy.','Pour into a tall glass. Top with whipped cream if you''re in your "treat" era.','Dust matcha on top for the barista finish.'],
ARRAY['Cold + creamy smooths matcha''s natural edge','Blending makes it feel like dessert without being dessert'],
true),

('Iced Matcha Latte',
'The classic. Clean layers, café energy, zero chaos (unless you want it).',
'https://images.unsplash.com/photo-1515823064-d6e0c04616a7?w=600&h=400&fit=crop',
'Drinks', '4 min',
ARRAY['3 g Nastea Rituals Matcha','30 ml water','120 ml cold milk','30 ml maple syrup or honey (optional)','Ice'],
ARRAY['Whisk matcha with water until frothy.','Add sweetener to a glass (if using) + fill 1/3 with ice.','Pour in milk.','Gently pour matcha over the milk for that layered look.'],
ARRAY['Milk makes it creamy, ice makes it crisp','Whisking keeps it smooth—not clumpy'],
true),

('Hot Matcha Latte',
'Warm, cosy, and quietly powerful—the "I have my life together" cup.',
'https://images.unsplash.com/photo-1578662996442-48f60103fc96?w=600&h=400&fit=crop',
'Drinks', '5 min',
ARRAY['3 g Nastea Rituals Matcha','20 ml water','150–200 ml hot milk','15 ml condensed milk (optional)','Sweetener (optional)'],
ARRAY['Sift matcha, add water (and condensed milk if using), whisk smooth.','Steam/heat milk until hot with a little foam.','Pour milk into matcha, hold foam back, then top.'],
ARRAY['Warm milk rounds out matcha''s flavour','Makes it taste extra silky'],
true),

('Strawberry Matcha Latte',
'A green-and-pink situation. Sweet, creamy, and extremely camera-ready.',
'https://images.unsplash.com/photo-1553979459-d2229ba7433a?w=600&h=400&fit=crop',
'Drinks', '4 min',
ARRAY['3 g Nastea Rituals Matcha','30 ml water (room temp)','120 ml cold milk','Strawberry crush/syrup (about 30 ml)','Ice'],
ARRAY['Whisk matcha + water until frothy.','Add strawberry syrup to glass + fill 1/3 with ice.','Pour milk over it.','Layer matcha on top.'],
ARRAY['Berry sweetness + matcha''s creamy bitterness = the perfect balanced but fun drink'],
true),

('Blackcurrant Matcha Latte',
'A little tart, a little sweet, very "I discovered this first."',
'https://images.unsplash.com/photo-1501443762994-82bd5dace89a?w=600&h=400&fit=crop',
'Drinks', '4 min',
ARRAY['3 g Nastea Rituals Matcha','30 ml lukewarm water','120 ml cold milk','Blackcurrant crush/syrup (about 30 ml)','Ice'],
ARRAY['Whisk matcha + water until smooth and frothy.','Add blackcurrant syrup + ice to glass.','Add milk.','Layer matcha on top.'],
ARRAY['Blackcurrant''s tang cuts through the creaminess','Tastes bright, not heavy'],
true),

('Coconut Cloud Matcha',
'Matcha, but make it fluffy. Light, creamy, and looks like a flex on purpose.',
'https://images.unsplash.com/photo-1511690743698-d9d85f2fbf38?w=600&h=400&fit=crop',
'Drinks', '6 min',
ARRAY['3 g Nastea Rituals Matcha','10 ml cold milk','30 ml whipped cream','10 ml maple syrup (optional)','150 ml coconut water','Ice'],
ARRAY['Whisk matcha with a splash of milk until lump-free.','In a cup: whipped cream + sweetener, add matcha, froth ~2 minutes until thick.','Glass: ice + coconut water.','Gently layer the matcha cloud on top.'],
ARRAY['Coconut water keeps it crisp','The cloud makes it indulgent without being heavy'],
true),

('White Chocolate Matcha',
'Creamy, sweet, and suspiciously addictive. It''s dessert energy without the dessert commitment.',
'https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=600&h=400&fit=crop',
'Drinks', '4 min',
ARRAY['4 g Nastea Rituals Matcha','40 ml lukewarm water','120 ml cold milk','White chocolate crush/syrup (about 30 ml)','Ice','Sweetener (optional)'],
ARRAY['Whisk matcha + water until frothy.','Add white chocolate syrup + ice to glass.','Pour in milk.','Layer matcha on top.'],
ARRAY['White chocolate softens matcha''s edge','Turns it into a creamy treat'],
true),

('Berry Matcha Latte',
'If you can''t pick a berry, don''t. This is the easy, crowd-pleasing option.',
'https://images.unsplash.com/photo-1553979459-d2229ba7433a?w=600&h=400&fit=crop',
'Drinks', '4 min',
ARRAY['4 g Nastea Rituals Matcha','40 ml lukewarm water','120 ml cold milk','Berry crush/syrup (about 30 ml)','Ice'],
ARRAY['Whisk matcha + water.','Add berry syrup + ice to glass.','Add milk.','Layer matcha on top.'],
ARRAY['Berry flavour lifts matcha','Makes it taste lighter and more summer'],
true),

('Watermelon Matcha Tonic',
'The fizzy one. Bright, refreshing, and slightly chaotic (in the best way).',
'https://images.unsplash.com/photo-1544787219-7f47ccb76574?w=600&h=400&fit=crop',
'Drinks', '4 min',
ARRAY['3 g Nastea Rituals Matcha','30 ml lukewarm water','150 ml tonic water','25 ml watermelon syrup','Ice'],
ARRAY['Whisk matcha + water until smooth.','Add watermelon syrup + ice to glass.','Pour tonic water.','Layer matcha on top. Stir if you''re feeling wild.'],
ARRAY['Tonic brings the sparkle','Watermelon makes it playful','Matcha keeps it grounded'],
true),

('Mango Matcha Latte',
'Tropical, creamy, and very "holiday brain" even on a Tuesday.',
'https://images.unsplash.com/photo-1515823064-d6e0c04616a7?w=600&h=400&fit=crop',
'Drinks', '4 min',
ARRAY['3 g Nastea Rituals Matcha','30 ml water','80–100 ml cold milk','40 ml mango juice','15 ml sweetener (optional)','Ice'],
ARRAY['Whisk matcha with water + sweetener until frothy; whisk in cold milk.','Add mango juice + ice to glass.','Pour matcha mixture over the top.'],
ARRAY['Mango''s sweetness makes matcha taste softer','More dessert-adjacent'],
true),

('Strawberry Matcha Foam Latte',
'Layered, foamy, and frankly too pretty to drink (but you will).',
'https://images.unsplash.com/photo-1553979459-d2229ba7433a?w=600&h=400&fit=crop',
'Drinks', '5 min',
ARRAY['3 g Nastea Rituals Matcha','30 ml water','80–100 ml cold milk','30 ml whipping cream','30 ml strawberry syrup','Ice'],
ARRAY['Whisk matcha + water until frothy.','Glass: ice + cold milk + matcha.','Froth cream + strawberry syrup until foamy.','Spoon foam on top.'],
ARRAY['Foam gives you that dessert texture','The base stays clean and balanced'],
true);
