// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wspnoeezvlobxuhkeqip.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndzcG5vZWV6dmxvYnh1aGtlcWlwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTEwNDY1MDksImV4cCI6MjA2NjYyMjUwOX0.ARlIjMOuDORYke5841_7yqbL5kyYGq0qDl3Ocn_65DI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);